-define(FC_ARRAYCOLLECTION, "flex.messaging.io.ArrayCollection").
-define(FC_OBJECTPROXY, "flex.messaging.io.ObjectProxy").
-define(FC_REMOTINGMESSAGE, "flex.messaging.messages.RemotingMessage").
-define(FC_COMMANDMESSAGE, "flex.messaging.messages.CommandMessage").
